### PR TITLE
Empty World

### PR DESCRIPTION
**Pull request by MALW3R3**
@Mareckoo01 Hello can you give me example how to do it in mcprotocollib localproxy, when i join it will be empty world can you do it please ?

### CODE REVIEW

**Comment by Johni0702** [comment]
I have no idea what you're trying to do/say.

**Comment by Mareckoo01** [comment]
@MALW3R3 
- Learn more Java
- Learn basic usage of github
- Read code
- Make what you want

Before you ask, there is a site called Google and you can find answers to your questions if you use it..
That will be the best way.

**Comment by MALW3R3** [comment]
@Johni0702 
When i join localhost it will be proxy/empty world
@Mareckoo01 
I try to send LoginSucces etc and there's error i can only send to play ServerJoinGame.
If you want i can pay for it.

**Comment by Mareckoo01** [comment]
@MALW3R3 do as i said in my last reply or find someone who will do it for money, maybe ask on spigotmc.org forum in
Services & Recruitment - v2
_Hiring - Developers_


**don't forget to read rules.**

**Comment by MALW3R3** [comment]
@Mareckoo01 
Can you help me man ? I know you can do it that very well that i write to you bcs you know mcprotocollib and java very well.
I can pay you for it, because i need it

**Comment by Mareckoo01** [comment]
@MALW3R3 i told you to find someone else because i don't have time to do it.

**Pull request closed without merging**
